package com.koala.pep.mapper;

import com.koala.pep.model.Account;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AccountMapper {

    int transferOut(@Param("out_user") String out_user, @Param("money") Double money);

    int transferIn(@Param("in_user") String in_user, @Param("money") Double money);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun May 03 15:11:30 CST 2020
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun May 03 15:11:30 CST 2020
     */
    int insertSelective(Account record);

}