package com.koala.pep.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.pk_user
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private String pkUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.user_name
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.password
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.real_name
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.email
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.phone
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.creator
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.creationtime
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private Date creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.modifier
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliff_user.modifiedtime
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    private Date modifiedtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.pk_user
     *
     * @return the value of cliff_user.pk_user
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public String getPkUser() {
        return pkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.pk_user
     *
     * @param pkUser the value for cliff_user.pk_user
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setPkUser(String pkUser) {
        this.pkUser = pkUser == null ? null : pkUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.user_name
     *
     * @return the value of cliff_user.user_name
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.user_name
     *
     * @param userName the value for cliff_user.user_name
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.password
     *
     * @return the value of cliff_user.password
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.password
     *
     * @param password the value for cliff_user.password
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.real_name
     *
     * @return the value of cliff_user.real_name
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.real_name
     *
     * @param realName the value for cliff_user.real_name
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.email
     *
     * @return the value of cliff_user.email
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.email
     *
     * @param email the value for cliff_user.email
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.phone
     *
     * @return the value of cliff_user.phone
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.phone
     *
     * @param phone the value for cliff_user.phone
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.creator
     *
     * @return the value of cliff_user.creator
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.creator
     *
     * @param creator the value for cliff_user.creator
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.creationtime
     *
     * @return the value of cliff_user.creationtime
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.creationtime
     *
     * @param creationtime the value for cliff_user.creationtime
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.modifier
     *
     * @return the value of cliff_user.modifier
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.modifier
     *
     * @param modifier the value for cliff_user.modifier
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliff_user.modifiedtime
     *
     * @return the value of cliff_user.modifiedtime
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public Date getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliff_user.modifiedtime
     *
     * @param modifiedtime the value for cliff_user.modifiedtime
     *
     * @mbg.generated Mon Jan 20 12:22:53 CST 2020
     */
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }
}